### ISSUE TITLE
getting wrong date for some releases

### ISSUE THREAD

**Issue by phirestalker** [tweitzel/beets-recordingdate#3]
Example:
Crime wave by 50 cent is showing a date of 1973. I go to the page on MusicBrainz for the recording
https://musicbrainz.org/recording/b0135a23-aa05-49fe-8b06-91c8ce9ccb59
but I do not see any relations that show 1973.

Let me know what other information you need.

**Comment by tweitzel** [comment]
It picked up on the samples he used. I don’t have an ETA when I’ll get back to this project, but if someone wants to pick up the ball, it needs a check on type of relationship. Should probably only do “edits” or “remasters.”

**Comment by tweitzel** [comment]
It looks like the sample relation is new to musicbrainz since I wrote this thing in the 1800s, so apologies for not predicting the future adequately.

**Comment by phirestalker** [comment]
I have a fork going of this plugin. I was really only hoping for some insight, not placing blame. You have provided somewhere for me to look.

**Comment by phirestalker** [comment]
OK, fixed it on my branch.

**Comment by tweitzel** [comment]
Sweet! Can you do a PR so I can merge it upstream? (only 3 lines it seems but it’s cleaner for all involved)

**Comment by phirestalker** [comment]
I have done other changes before this one. Do you want them all in the PR?

**Comment by tweitzel** [comment]
Sure.

**Comment by phirestalker** [comment]
I found another relation that should probably be ignored. I would like your input.
It is called covers or other versions. All relations of this type should be from another artist, correct? Is it a good idea to ignore them?

**Comment by tweitzel** [comment]
Yes. It might actually be better to whitelist relationship types via a config variable at this time.

A nice safety measure would be to compare the artist ID that comes with the related work and discard the relation if it changes.

**Comment by tweitzel** [comment]
Turns out x['recording'] on line 131 doesn't always have an 'artist' key or indeed any link back to the artist, so in the interests of keeping the number of gratuitous API calls down for now I'm going to put in a check for that and skip it if the key isn't there.

**Comment by phirestalker** [comment]
I noticed that the recording entity also has an artist-credit attribute. Does the ngs library expose that too? Should the plugin endeavor to use that instead?

**Comment by phirestalker** [comment]
Also, do you know where I can find an actual representation of every possible key in the dict returned by get_recording_by_id()?
If it exists it would allow me to work through these issues without asking so many stupid questions.

**Comment by tweitzel** [comment]
I believe this is the currentl schema for recording relationships. https://musicbrainz.org/relationships/recording-recording

I do not know if the artist-credit attribute is the right one, just because I haven’t delved into it. Its documentation is here https://musicbrainz.org/doc/Recording#Artist
